version: '3.8'

services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    image: discord_webhook:latest
    volumes:
      - ./:/app
    container_name: DiscordWebhook
    ports:
      - "5000:5000"
    restart: always
